###
# @prompt password
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name": "Matheus Tadao Momiy",
    "email": "matheusmomiy@zmail.com",
    "password": "{{password}}",
    "type": "admin"
}
